### ISSUE TITLE
raw_data subdirectory files

### ISSUE THREAD

**Issue by jackbrucesimpson** [patelhardip/amw#1]
Because I had some transfers fail partially and I couldn't overwrite them, I created a new raw_data subdirectory in the raw_data directory with the real data (soetanto/raw_data/raw_data). Would it be possible for you to please delete the files in the current raw_data directory and move the files in the subdirectory up into the parent directory?

**Comment by hp2048** [comment]
[Soetanto_Files.txt](https://github.com/patelhardip/amw/files/1079804/Soetanto_Files.txt) file contains the list of files for the run. Could you please check the md5sum values on your side to make sure that you have everything in there correctly? I can see couple of files that are empty. If you can make sure all is good, then I can proceed with the analyses. Cheers

**Comment by jackbrucesimpson** [comment]
Hi Hadip, sorry about the late reply, I had meetings after the workshop. For some reason the files uploaded ended up being corrupted and the list was incomplete. I just gave it another go creating a new directory raw_data/reads which I hope looks ok now. Thanks so much!

**Comment by hp2048** [comment]
[Soetanto_Files.txt](https://github.com/patelhardip/amw/files/1083445/Soetanto_Files.txt) now contains the list of files that will be processed. I will delete rest of them. Please keep a copy of the files as I will not be archiving these files. Cheers mate.
